name: hotel_test
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  http: ^1.1.0
  flutter_custom_carousel_slider: ^1.2.0
  meta: ^1.9.1
  auto_route: ^7.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: SF-Pro-Display
      fonts:
      - asset: assets/fonts/SF-Pro-Display-Black.otf
        weight: 900
      - asset: assets/fonts/SF-Pro-Display-BlackItalic.otf
        weight: 900
        style: italic
      - asset: assets/fonts/SF-Pro-Display-Bold.otf
        weight: 700
      - asset: assets/fonts/SF-Pro-Display-BoldItalic.otf
        weight: 700
        style: italic
      - asset: assets/fonts/SF-Pro-Display-Heavy.otf
        weight: 800
      - asset: assets/fonts/SF-Pro-Display-HeavyItalic.otf
        weight: 800
        style: italic
      - asset: assets/fonts/SF-Pro-Display-Light.otf
        weight: 300
      - asset: assets/fonts/SF-Pro-Display-LightItalic.otf
        weight: 300
        style: italic
      - asset: assets/fonts/SF-Pro-Display-Medium.otf
        weight: 500
      - asset: assets/fonts/SF-Pro-Display-MediumItalic.otf
        weight: 500
        style: italic
      - asset: assets/fonts/SF-Pro-Display-Regular.otf
        weight: 400
      - asset: assets/fonts/SF-Pro-Display-RegularItalic.otf
        weight: 400
        style: italic
      - asset: assets/fonts/SF-Pro-Display-Semibold.otf
        weight: 600
      - asset: assets/fonts/SF-Pro-Display-SemiboldItalic.otf
        weight: 600
        style: italic
      - asset: assets/fonts/SF-Pro-Display-Thin.otf
        weight: 200
      - asset: assets/fonts/SF-Pro-Display-ThinItalic.otf
        weight: 200
        style: italic
      - asset: assets/fonts/SF-Pro-Display-Ultralight.otf
        weight: 100
      - asset: assets/fonts/SF-Pro-Display-UltralightItalic.otf
        weight: 100
        style: italic
